CREATE TABLE tbl_product (
	-- 상품번호
	pno INT AUTO_INCREMENT PRIMARY KEY,
	-- 상품 이름
	pname VARCHAR(200) NOT NULL,
	-- 상품 설명
	pdesc VARCHAR(200) NOT NULL,
	-- 상품 가격
	price INT NOT NULL,
	-- 판매 여부(false)
	sale BOOLEAN DEFAULT FALSE,
	-- 상품 등록자
	writer VARCHAR(100) NOT NULL,
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP,
	moddate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM tbl_product;